name: Clean up old images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # 매주 일요일 자정에 실행

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write 

    steps:
      - name: Delete old packages
        uses: actions/delete-package-versions@v3
        with:
          package-name: neocode24
          package-type: 'container'
          min-versions-to-keep: 10
          ignore-versions: '^(latest|stable|v[0-9]+)$'
